---
config:
  theme: default
  layout: elk
  look: handDrawn
---
flowchart TB
 subgraph AppChildren["AppChildren"]
        E("KanbanCard")
        D("App")
        F("ThemePopover")
        G("BackgroundPopover")
        H("ColorPopover")
  end
    A["src/main.jsx"] --> B("ThemeProviderWrapper")
    B --> C("ThemeContext")
    C --> D
    D --> E & F & G & H
